<img src = 'https://github.com/insaid2018/Term-1/blob/master/Images/INSAID_Full%20Logo.png?raw=true' width="240" height="360">
# __Assignment: Numpy and Pandas__
### Level: 1

### 1. Create a null vector of size 7 but the third and last value as 2.

In [14]:
import numpy as np
def generate():
    val= np.zeros(7)
    val[2]=2
    val[-1]=2
    print(val)
    return # your variable 
generate()

[0. 0. 2. 0. 0. 0. 2.]


### 2. Create a vector of size 9 with values ranging from 0 to 2, both excluded.

In [18]:
import numpy as np
def generate():
    # Write your code here
    vec = np.linspace(0,2,9,endpoint=True)
    print(vec)
    return # your variable
generate()

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


### 3. Convert the first character of each element in a series to uppercase? And return the new series.

In [25]:
def square(x):
    return x ** 2
s = pd.Series([2,3,4])
a=s.apply(square)
a

0     4
1     9
2    16
dtype: int64

In [31]:
import pandas as pd
series = pd.Series(['how', 'to', 'learn', 'data science?'])
def generate():
    # your code
    new_series = series.apply(upp)
    return new_series # your variable for new series
def upp(x):
    return x[0].upper() + x[1:]
    
    
generate() 

0              How
1               To
2            Learn
3    Data science?
dtype: object

### 4. Given a 3*3 matrix named matrix_fab, From each element of this matrix subtract the mean of that row, name this matrix as matrix_sub. Divide each element of this matrix by twice of the largest element to get matrix_norm. Print it out.

In [47]:
import numpy as np
arr = np.arange(0,9)                                
matrix_fab = arr.reshape(3,3)
def generate():
    print(matrix_fab)
    matrix_sub=matrix_fab-matrix_fab.mean(axis=1 , keepdims= True)
    max=matrix_sub.max()
    matrix_norm = matrix_sub/(2*max)
    print(matrix_norm)
    # print matrix_norm
    return None
generate()

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[-0.5  0.   0.5]
 [-0.5  0.   0.5]
 [-0.5  0.   0.5]]


In [52]:
import numpy as np
x  = np.array([[1,2,3],[4,5,6]])
print(x.shape)
# (2, 3)

print(np.sum(x, keepdims=True).shape)
# (1, 1)

print(np.sum(x, keepdims=True))
# array([[21]]) <---the reault is still a 1x1 array

print(np.sum(x, keepdims=False).shape)
# ()

print(np.sum(x, keepdims=False))
# 21 <--- the result is an integer with no dimesion

(2, 3)
(1, 1)
[[21]]
()
21


### 5. Create a random vector of size 12 , sort it in decreasing order, make 4*3 array using it.
Hint: use reshape and sort function.

In [65]:
import numpy as np
def generate():
    # Write your code here
    rand_vect = np.random.random(12)
    print(rand_vect)
    print(np.array(sorted(rand_vect,reverse=True)).reshape(4,3))
    return # your variable
generate()

[0.74114711 0.14614688 0.85224386 0.58793672 0.13269808 0.45947365
 0.82924514 0.69907449 0.39026486 0.25359508 0.26426104 0.5443838 ]
[[0.85224386 0.82924514 0.74114711]
 [0.69907449 0.58793672 0.5443838 ]
 [0.45947365 0.39026486 0.26426104]
 [0.25359508 0.14614688 0.13269808]]


### 6. Below is Python dictionary data and Python list labels. Create a DataFrame df from this dictionary data which has index as labels. Select the rows where the age is missing, i.e. is NaN.

In [78]:
import numpy as np
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
import pandas as pd
def generate():
    # Write your code here
    df= pd.DataFrame(data,index=labels)
    return df[df['age'].isnull()] # your variable
generate()



animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes

In [84]:
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df= pd.DataFrame(data,index=labels)

### 7. From the give dataframe df, in the 'animal' column change the 'dog' entries to 'Labrador', change the age in row 'd' to 2.7 and calculate the mean age (name it mean_age) for each different animal in df. Print df and return mean_age.

In [14]:
import pandas as pd
import numpy as np
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(data, index=labels)
def generate():
    print(df.head())
    df['animal']=df['animal'].replace('dog','Labrador')
    df.loc['d','age']=2.7
    print(df.head())
    mean_age=df.groupby('animal').age.mean()
    # mean_age = df.groupby('animal')['age'].mean()
    mean_age = df.groupby('animal')[['age','visits']].mean()
    # write your code here
    # Also print df
    return mean_age # your variable i.e mean_age
generate()

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
     animal  age  visits priority
a       cat  2.5       1      yes
b       cat  3.0       3      yes
c     snake  0.5       2       no
d  Labrador  2.7       3      yes
e  Labrador  5.0       2       no


age  visits
animal                 
Labrador  4.425     2.0
cat       2.500     2.0
snake     2.500     1.5

### 8.  From the given dataframe get the positions where values of two columns match?

In [10]:
import pandas as pd
import numpy as np
df = pd.DataFrame({'fruit1': np.random.choice(['apple', 'orange', 'banana'], 10),
                    'fruit2': np.random.choice(['apple', 'orange', 'banana'], 10)})
def generate():
    # your code here
    return None
generate()

### 9. Find the positions of numbers that are multiples of 4 from a series? Print series and return position. Hint: use argwhere.

In [7]:
import pandas as pd
import numpy as np
series = pd.Series(np.random.randint(1, 10, 7))
def generate():
    # your code here
    # print(series)
    return # your variable
generate()

### 10. Stack two given series vertically and horizontally ? Print out both.

In [8]:
import pandas as pd
import numpy as np
series1 = pd.Series(range(5))
series2 = pd.Series(list('abcde'))
def generate():
    # your code 
    # print out both vertically and horizontally stacked series.
    return None
generate()